name: Pre-release

on:
  push:
    branches:
      - "rc/*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  dry-run-release-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node version and cache dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install deps
        run: yarn install

      - name: Install peer deps
        run: yarn peer

      - name: Build
        run: yarn build

      - name: create dry run release
        run: npx semantic-release --dry-run
        id: dry-run-release-version
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      new-release-published: ${{ steps.dry-run-release-version.outputs.new-release-published }}
      new-release-version: ${{ steps.dry-run-release-version.outputs.new-release-version }}

  release-beta:
    runs-on: ubuntu-latest
    needs: dry-run-release-version
    if: needs.dry-run-release-version.outputs.new-release-published == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Install peer
        run: yarn peer

      - name: Build
        run: yarn build

      - name: create release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
